# 车辆基本参数
wheel_radius: 0.210
wheel_width: 0.04
wheel_base: 0.660
wheel_tread: 0.645
vehicle_mass: 150.0
vehicle_length: 1.320
vehicle_width: 0.765
vehicle_height: 1.49
minimum_turning_radius: 2.0
maximum_steering_angle: 25.0  #deg